export type NyAreaKind = "city" | "borough" | "neighborhood" | "county";

export type NyArea = {
  slug: string;
  name: string;
  shortLocation: string;
  kind: NyAreaKind;
  parent: string | null;
  areas: string[];
  nearby: string[];
  localContext: string;
  accessNotes: string[];
  searchIntent: string;
  marketSignals: { keyword: string; monthlySearches: number; cpc: number };
};

export const NY_AREAS: NyArea[] = [
  {
    slug: "new-york-ny",
    name: "New York City",
    shortLocation: "NYC",
    kind: "city",
    parent: null,
    areas: ["Manhattan", "Brooklyn", "Queens", "Bronx", "Staten Island"],
    nearby: ["manhattan-ny", "brooklyn-ny", "queens-ny", "bronx-ny", "staten-island-ny"],
    localContext: "New York City is not one uniform locksmith market. Apartment towers and prewar walk-ups in Manhattan, brownstone and rowhouse blocks in Brooklyn, mixed apartment and detached-home neighborhoods in Queens, dense multifamily areas in the Bronx, and lower-density residential streets on Staten Island all create different access situations.",
    accessNotes: [
      "NYC has five boroughs and 59 community districts, so a useful request starts with the exact borough, neighborhood and service address rather than a generic citywide promise.",
      "Apartment and co-op buildings often add a building-entry or management layer to a unit-level lock problem; single- and multifamily homes create a different access context.",
      "Street congestion, bridge and tunnel crossings, parking constraints and provider service areas make real acceptance more meaningful than a generic citywide ETA.",
    ],
    searchIntent: "High-intent NYC searches center on finding a locksmith by borough or neighborhood. This page is the citywide hub and routes people into the more specific New York pages.",
    marketSignals: { keyword: "locksmith nyc", monthlySearches: 4400, cpc: 22.29 },
  },
  {
    slug: "manhattan-ny",
    name: "Manhattan",
    shortLocation: "Manhattan, NYC",
    kind: "borough",
    parent: "new-york-ny",
    areas: ["Chelsea", "Upper West Side", "Upper East Side", "Harlem", "Midtown", "West Village", "Lower East Side", "Washington Heights"],
    nearby: ["chelsea-ny", "upper-west-side-ny", "harlem-ny", "upper-east-side-ny", "new-york-ny"],
    localContext: "Manhattan combines prewar apartment and co-op buildings, brownstones and townhouses, postwar high-rises, newer residential towers and mixed-use buildings. The lock at the apartment door is only one part of the access picture when a lobby, doorman, building manager or shared entrance is involved.",
    accessNotes: [
      "Manhattan Community Boards identify distinct neighborhoods such as Chelsea, the Upper West Side, Upper East Side and Central Harlem, each with different residential building patterns.",
      "Broadway, the avenues and dense cross-town blocks mean a provider's actual service area and acceptance matter more than a blanket Manhattan-wide arrival claim.",
      "Rekeys and lock changes are often planned access-control jobs after a move, tenant change or key-possession change, while apartment lockouts are the most time-sensitive path.",
    ],
    searchIntent: "Manhattan search demand is strong enough to justify both a borough page and selected neighborhood pages rather than forcing every query into a generic NYC page.",
    marketSignals: { keyword: "locksmith manhattan ny", monthlySearches: 2400, cpc: 24.50 },
  },
  {
    slug: "brooklyn-ny",
    name: "Brooklyn",
    shortLocation: "Brooklyn, NYC",
    kind: "borough",
    parent: "new-york-ny",
    areas: ["Park Slope", "Midwood", "Bay Ridge", "Williamsburg", "Bushwick", "Greenpoint", "Crown Heights", "Flatbush"],
    nearby: ["park-slope-ny", "midwood-ny", "bay-ridge-ny", "queens-ny", "new-york-ny"],
    localContext: "Brooklyn's housing ranges from brownstone and rowhouse blocks to apartment buildings, mixed-use corridors, multifamily houses and detached or semi-detached homes farther south. That makes 'locksmith Brooklyn' a broad intent covering very different doors, cylinders and building-access situations.",
    accessNotes: [
      "Park Slope's rowhouses and apartment conversions are different from Midwood's mix of apartment houses and detached homes or Bay Ridge's rowhouses, houses and larger apartment buildings.",
      "Major commercial corridors such as Fifth Avenue, Flatbush Avenue, Atlantic Avenue and Kings Highway sit beside residential blocks, so the service address should drive matching rather than a borough-level dispatch assumption.",
      "Automotive searches are meaningful in Brooklyn, but Trusted Locksmith's current vehicle offer remains standard lockout entry only—not key cutting, fob programming or ignition work.",
    ],
    searchIntent: "Brooklyn has enough standalone and neighborhood-level demand to support a borough hub plus a selective neighborhood cluster.",
    marketSignals: { keyword: "locksmith brooklyn", monthlySearches: 2400, cpc: 20.59 },
  },
  {
    slug: "queens-ny",
    name: "Queens",
    shortLocation: "Queens, NYC",
    kind: "borough",
    parent: "new-york-ny",
    areas: ["Astoria", "Flushing", "Jamaica", "Forest Hills", "Bayside", "Woodside", "Jackson Heights", "Long Island City"],
    nearby: ["astoria-ny", "flushing-ny", "jamaica-ny", "forest-hills-ny", "brooklyn-ny"],
    localContext: "Queens has one of the broadest housing mixes in New York City: large apartment buildings, co-ops and condos, attached houses, two-family homes and detached residential streets. Local locksmith intent therefore behaves more like a collection of neighborhood markets than a single borough-wide market.",
    accessNotes: [
      "Astoria, Flushing, Jamaica and Forest Hills each show meaningful standalone locksmith demand and deserve their own local pages.",
      "Queens addresses can sit near major transit and commercial centers or on lower-density residential streets, which changes parking, access and the likely provider service radius.",
      "Vehicle lockout demand is material in Queens, but the current Trusted Locksmith scope remains entry-only and excludes replacement keys and programming.",
    ],
    searchIntent: "Queens should be structured as a borough hub with high-demand neighborhood pages underneath it.",
    marketSignals: { keyword: "locksmith queens", monthlySearches: 1000, cpc: 20.59 },
  },
  {
    slug: "bronx-ny",
    name: "Bronx",
    shortLocation: "The Bronx, NYC",
    kind: "borough",
    parent: "new-york-ny",
    areas: ["Fordham", "Riverdale", "Kingsbridge", "Parkchester", "Morris Park", "Pelham Bay", "Concourse", "Throgs Neck"],
    nearby: ["manhattan-ny", "yonkers-ny", "new-york-ny", "queens-ny"],
    localContext: "The Bronx includes dense apartment corridors, rowhouses and multifamily homes as well as lower-density residential areas such as Riverdale and parts of the East Bronx. A borough-wide locksmith request therefore needs the actual neighborhood and address before matching can be credible.",
    accessNotes: [
      "Fordham, the Grand Concourse and Parkchester represent dense apartment and mixed-use environments, while Riverdale and parts of the East Bronx include more house-based access situations.",
      "Cross-borough travel and local traffic make a real provider acceptance a better signal than an automatically displayed ETA.",
      "Bronx automotive-locksmith searches are substantial, but this launch offer is standard vehicle entry only.",
    ],
    searchIntent: "The Bronx has strong borough-level demand; neighborhood expansion should be selective until individual submarket demand justifies more pages.",
    marketSignals: { keyword: "locksmith bronx ny", monthlySearches: 880, cpc: 16.21 },
  },
  {
    slug: "staten-island-ny",
    name: "Staten Island",
    shortLocation: "Staten Island, NYC",
    kind: "borough",
    parent: "new-york-ny",
    areas: ["St. George", "Tompkinsville", "West Brighton", "Port Richmond", "New Dorp", "Great Kills", "Eltingville", "Tottenville"],
    nearby: ["brooklyn-ny", "new-york-ny"],
    localContext: "Staten Island is a different access market from the denser boroughs: detached and semi-detached homes, townhouses and lower-rise apartment buildings are more common across many neighborhoods. Service-area matching is especially important because travel distances across the island can be substantial.",
    accessNotes: [
      "North Shore neighborhoods such as St. George and Tompkinsville have a more urban mix, while areas farther south and east include many house and townhouse access situations.",
      "Hylan Boulevard, Richmond Avenue and the island's expressway network shape travel between neighborhoods, so availability should be address-specific.",
      "Home lockouts, planned rekeys and standard lock changes fit the island's residential mix without needing a separate generic call-out fee.",
    ],
    searchIntent: "Staten Island has enough borough-level demand for a dedicated hub, but only a limited number of ZIP/neighborhood terms currently justify separate pages.",
    marketSignals: { keyword: "locksmith staten island", monthlySearches: 720, cpc: 11.44 },
  },
  {
    slug: "chelsea-ny",
    name: "Chelsea",
    shortLocation: "Chelsea, Manhattan",
    kind: "neighborhood",
    parent: "manhattan-ny",
    areas: ["West 14th Street", "West 23rd Street", "West 26th Street", "Sixth Avenue", "Eighth Avenue", "Ninth Avenue", "Tenth Avenue", "Eleventh Avenue"],
    nearby: ["manhattan-ny", "upper-west-side-ny", "new-york-ny"],
    localContext: "Chelsea sits on Manhattan's West Side and is formally associated with Manhattan Community Board 4. The neighborhood mixes prewar apartment buildings, townhouses, converted loft and industrial buildings, mixed-use avenues and newer residential towers closer to the Hudson side.",
    accessNotes: [
      "Community Board 4 describes its district as Chelsea and Clinton/Hell's Kitchen, covering the West Side from roughly 14th to 59th Streets with different eastern boundaries north and south of 26th Street.",
      "Older walk-ups and converted loft buildings can have different door and hardware conditions from newer doorman or elevator buildings.",
      "Ninth and Tenth Avenue residential blocks sit close to busy commercial and visitor traffic, which makes exact-address matching more useful than a neighborhood-wide arrival promise.",
    ],
    searchIntent: "Chelsea has unusually strong neighborhood-level locksmith demand for Manhattan and merits a dedicated local page.",
    marketSignals: { keyword: "locksmith chelsea nyc", monthlySearches: 320, cpc: 12.78 },
  },
  {
    slug: "upper-west-side-ny",
    name: "Upper West Side",
    shortLocation: "Upper West Side, Manhattan",
    kind: "neighborhood",
    parent: "manhattan-ny",
    areas: ["Broadway", "Amsterdam Avenue", "Columbus Avenue", "Central Park West", "Riverside Drive", "Lincoln Square", "Manhattan Valley"],
    nearby: ["manhattan-ny", "harlem-ny", "upper-east-side-ny", "new-york-ny"],
    localContext: "The Upper West Side, together with Lincoln Square and Manhattan Valley in Community Board 7, is dominated by apartment living but includes brownstones, townhouses, co-ops, condos and newer high-rise buildings. A unit lockout can therefore be separate from building-entry access.",
    accessNotes: [
      "Broadway, Amsterdam and Columbus Avenues run through dense residential blocks between Central Park and Riverside Drive.",
      "Prewar co-ops and rental buildings may have older mortise or cylinder hardware, while newer buildings can have different access-control arrangements.",
      "When a resident is locked out, confirming whether the problem is the apartment door, building entrance or both helps keep the request scope clear.",
    ],
    searchIntent: "Upper West Side demand is large enough to stand on its own instead of being buried inside a Manhattan page.",
    marketSignals: { keyword: "locksmith upper west side", monthlySearches: 210, cpc: 11.65 },
  },
  {
    slug: "harlem-ny",
    name: "Harlem",
    shortLocation: "Harlem, Manhattan",
    kind: "neighborhood",
    parent: "manhattan-ny",
    areas: ["Central Harlem", "West Harlem", "Sugar Hill", "Hamilton Heights", "125th Street", "Lenox Avenue", "Adam Clayton Powell Jr. Boulevard"],
    nearby: ["manhattan-ny", "upper-west-side-ny", "bronx-ny", "new-york-ny"],
    localContext: "Harlem locksmith intent spans a broad upper-Manhattan area with brownstones, rowhouses, walk-up apartments, larger apartment buildings and mixed-use avenues. Central Harlem is represented by Manhattan Community Board 10, while West and East Harlem sit in adjacent community districts.",
    accessNotes: [
      "Central Harlem's official community-board area runs between Central Park and the Harlem River with Fifth Avenue forming its eastern edge.",
      "Brownstone and townhouse entries can create different rekey or lock-change needs from apartment-unit doors in larger buildings.",
      "The commercial spine around 125th Street and the surrounding residential blocks make exact service-address capture essential before provider matching.",
    ],
    searchIntent: "Harlem search demand and high CPC indicate meaningful urgent/commercial intent, so a dedicated page is justified.",
    marketSignals: { keyword: "locksmith harlem nyc", monthlySearches: 170, cpc: 32.78 },
  },
  {
    slug: "upper-east-side-ny",
    name: "Upper East Side",
    shortLocation: "Upper East Side, Manhattan",
    kind: "neighborhood",
    parent: "manhattan-ny",
    areas: ["Lenox Hill", "Yorkville", "Park Avenue", "Lexington Avenue", "Third Avenue", "Second Avenue", "East End Avenue"],
    nearby: ["manhattan-ny", "upper-west-side-ny", "harlem-ny", "new-york-ny"],
    localContext: "The Upper East Side, including Lenox Hill and Yorkville in Community Board 8, combines prewar co-ops and rentals, townhouses, postwar apartment buildings and newer towers. Building-entry arrangements and unit-door hardware can vary significantly within a few blocks.",
    accessNotes: [
      "Community Board 8 identifies the Upper East Side together with Lenox Hill, Yorkville and Roosevelt Island.",
      "Park, Lexington, Third and Second Avenue corridors include dense residential and mixed-use buildings, while side streets add townhouses and smaller buildings.",
      "For apartment lockouts, the request should distinguish private-unit access from lobby or building-system access.",
    ],
    searchIntent: "The Upper East Side has sufficient standalone search demand to merit a dedicated neighborhood page.",
    marketSignals: { keyword: "locksmith upper east side", monthlySearches: 140, cpc: 12.98 },
  },
  {
    slug: "astoria-ny",
    name: "Astoria",
    shortLocation: "Astoria, Queens",
    kind: "neighborhood",
    parent: "queens-ny",
    areas: ["Ditmars-Steinway", "30th Avenue", "Broadway", "Steinway Street", "Astoria Boulevard", "31st Street", "21st Street"],
    nearby: ["queens-ny", "new-york-ny", "flushing-ny", "forest-hills-ny"],
    localContext: "Astoria has one of the strongest neighborhood-level locksmith search signals in Queens. Its housing mix includes apartment buildings, attached and semi-attached homes, small multifamily properties and mixed-use corridors around 30th Avenue, Broadway and Steinway Street.",
    accessNotes: [
      "Ditmars-Steinway and the residential streets around 31st Street differ from the busier retail corridors on Broadway and Steinway Street.",
      "Many Astoria buildings are small enough that a unit lockout may involve a landlord or shared entry as well as the apartment door.",
      "Vehicle and residential access both matter here, but car service remains standard entry only under the current product scope.",
    ],
    searchIntent: "Astoria is the strongest Queens neighborhood query in the current research and should be a first-wave page.",
    marketSignals: { keyword: "locksmith astoria queens", monthlySearches: 480, cpc: 18.09 },
  },
  {
    slug: "flushing-ny",
    name: "Flushing",
    shortLocation: "Flushing, Queens",
    kind: "neighborhood",
    parent: "queens-ny",
    areas: ["Downtown Flushing", "East Flushing", "Broadway Flushing", "Auburndale", "Kissena Park area", "Northern Boulevard", "Main Street"],
    nearby: ["queens-ny", "forest-hills-ny", "jamaica-ny", "new-york-ny"],
    localContext: "Flushing is a dense Queens center surrounded by varied residential subareas. Queens Community Board 7 identifies East Flushing, Broadway Flushing, Auburndale and the Kissena Park area among the local neighborhoods around Flushing.",
    accessNotes: [
      "Downtown around Main Street and Roosevelt Avenue has dense apartment and mixed-use buildings, while East and Broadway Flushing include more house-based residential blocks.",
      "Northern Boulevard and Main Street are major local corridors, but a provider still needs the exact address to know the building and access context.",
      "Apartment, multifamily and detached-home requests should not be treated as the same lockout scenario.",
    ],
    searchIntent: "Flushing has clear standalone search demand and a strong enough local identity to justify its own page.",
    marketSignals: { keyword: "locksmith in flushing ny", monthlySearches: 260, cpc: 7.11 },
  },
  {
    slug: "jamaica-ny",
    name: "Jamaica",
    shortLocation: "Jamaica, Queens",
    kind: "neighborhood",
    parent: "queens-ny",
    areas: ["Downtown Jamaica", "Jamaica Avenue", "Sutphin Boulevard", "Archer Avenue", "Hillside Avenue", "South Jamaica", "Jamaica Estates"],
    nearby: ["queens-ny", "forest-hills-ny", "flushing-ny", "new-york-ny"],
    localContext: "Jamaica is both a major transit/commercial center and a large residential area. Dense buildings around Jamaica Avenue, Sutphin Boulevard and Archer Avenue transition into lower-density multifamily and house-based streets farther from the downtown core.",
    accessNotes: [
      "Requests near the Jamaica transit hub can involve apartment or mixed-use buildings, while Jamaica Estates and adjacent residential sections have more house-based access situations.",
      "Busy commercial and transit streets make exact pickup/service location important for vehicle lockouts.",
      "High-intent search demand supports a dedicated page, but real provider identity and ETA should still appear only after acceptance.",
    ],
    searchIntent: "Jamaica's search volume and CPC support a dedicated Queens neighborhood page.",
    marketSignals: { keyword: "locksmith jamaica queens", monthlySearches: 170, cpc: 20.34 },
  },
  {
    slug: "forest-hills-ny",
    name: "Forest Hills",
    shortLocation: "Forest Hills, Queens",
    kind: "neighborhood",
    parent: "queens-ny",
    areas: ["Forest Hills Gardens", "Austin Street", "Continental Avenue", "108th Street", "Metropolitan Avenue", "Queens Boulevard"],
    nearby: ["queens-ny", "jamaica-ny", "flushing-ny", "new-york-ny"],
    localContext: "Forest Hills mixes apartment living with lower-density residential streets. Queens Community Board 6 notes both low- and high-density residential buildings, the planned Forest Hills Gardens community, and substantial rental, co-op and condominium apartment stock.",
    accessNotes: [
      "Austin Street and Continental Avenue form a busy shopping area near dense residential buildings, while Forest Hills Gardens has a very different house and townhouse pattern.",
      "Queens Boulevard adds larger apartment buildings and traffic, while Metropolitan Avenue reaches lower-density residential blocks.",
      "This mix makes it especially important to distinguish apartment-unit lockouts, house lockouts and planned rekey work.",
    ],
    searchIntent: "Forest Hills has a clear local query cluster and enough distinctive housing context for a dedicated page.",
    marketSignals: { keyword: "locksmith forest hills queens", monthlySearches: 140, cpc: 9.56 },
  },
  {
    slug: "midwood-ny",
    name: "Midwood",
    shortLocation: "Midwood, Brooklyn",
    kind: "neighborhood",
    parent: "brooklyn-ny",
    areas: ["Avenue J", "Avenue M", "Ocean Parkway", "Coney Island Avenue", "Kings Highway", "Ocean Avenue", "East 12th Street"],
    nearby: ["brooklyn-ny", "park-slope-ny", "bay-ridge-ny", "new-york-ny"],
    localContext: "Midwood is a south-central Brooklyn residential market with apartment buildings along major avenues and a substantial stock of detached, semi-detached and multifamily homes on quieter streets. It therefore produces both apartment and house access needs.",
    accessNotes: [
      "Avenue J, Avenue M, Coney Island Avenue and Kings Highway are major local commercial/transit corridors surrounded by residential blocks.",
      "Ocean Parkway and nearby streets include larger apartment buildings as well as house-based properties, so the correct service type matters.",
      "Midwood's strong neighborhood-specific search demand is unusual enough to justify a dedicated page in Wave 1.",
    ],
    searchIntent: "Midwood is one of Brooklyn's strongest non-branded neighborhood locksmith queries.",
    marketSignals: { keyword: "locksmith midwood", monthlySearches: 210, cpc: 0.78 },
  },
  {
    slug: "park-slope-ny",
    name: "Park Slope",
    shortLocation: "Park Slope, Brooklyn",
    kind: "neighborhood",
    parent: "brooklyn-ny",
    areas: ["Fifth Avenue", "Seventh Avenue", "Prospect Park West", "Union Street", "Ninth Street", "Fourth Avenue"],
    nearby: ["brooklyn-ny", "midwood-ny", "bay-ridge-ny", "new-york-ny"],
    localContext: "Park Slope is known for brownstone and rowhouse blocks, apartment conversions and larger apartment buildings around the neighborhood's major avenues. Lock needs can therefore range from a single apartment cylinder to multiple-entry townhouse or multifamily access.",
    accessNotes: [
      "Fifth and Seventh Avenues are active mixed-use corridors, while side streets toward Prospect Park contain many rowhouses and brownstones.",
      "Fourth Avenue has a different building pattern with larger and newer residential development mixed with older properties.",
      "Rekeying can be especially relevant after a move or key-possession change in a townhouse, condo or multifamily property.",
    ],
    searchIntent: "Park Slope has enough local search demand and distinct housing character for a first-wave neighborhood page.",
    marketSignals: { keyword: "locksmith park slope", monthlySearches: 90, cpc: 7.54 },
  },
  {
    slug: "bay-ridge-ny",
    name: "Bay Ridge",
    shortLocation: "Bay Ridge, Brooklyn",
    kind: "neighborhood",
    parent: "brooklyn-ny",
    areas: ["Third Avenue", "Fifth Avenue", "86th Street", "Shore Road", "Fourth Avenue", "Fort Hamilton"],
    nearby: ["brooklyn-ny", "park-slope-ny", "midwood-ny", "staten-island-ny"],
    localContext: "Bay Ridge combines rowhouses, detached and semi-detached homes, multifamily buildings and larger apartment properties. The commercial corridors on Third and Fifth Avenues sit close to quieter residential streets running toward Shore Road.",
    accessNotes: [
      "Third Avenue and Fifth Avenue carry much of the neighborhood's retail activity, while 86th Street is another major local corridor.",
      "House, townhouse and apartment lockouts all occur within the same neighborhood, so a generic 'Brooklyn lockout' description is not specific enough.",
      "Planned rekeys and lock changes fit the neighborhood's mix of owner-occupied and multifamily properties.",
    ],
    searchIntent: "Bay Ridge's neighborhood-level demand supports a dedicated page rather than relying only on the Brooklyn hub.",
    marketSignals: { keyword: "locksmith bay ridge", monthlySearches: 90, cpc: 9.95 },
  },
  {
    slug: "buffalo-ny",
    name: "Buffalo",
    shortLocation: "Buffalo, NY",
    kind: "city",
    parent: null,
    areas: ["Elmwood-Bidwell", "Allentown", "North Park", "West Side", "Parkside", "University Heights", "South Park", "First Ward"],
    nearby: ["rochester-ny", "syracuse-ny", "albany-ny"],
    localContext: "Buffalo's official planning map identifies distinct neighborhoods including Elmwood-Bidwell, Allentown, North Park, Parkside, the West Side, University Heights and South Park. The housing mix includes single-family homes, Buffalo doubles, multifamily properties and apartment buildings.",
    accessNotes: [
      "Elmwood-Bidwell and Allentown combine older residential buildings with active mixed-use streets, while North Park and Parkside have a more house-based residential pattern.",
      "Buffalo doubles and other two-family homes create multi-entry and rekey situations that differ from a single apartment lockout.",
      "Winter weather can add urgency to a lockout, but the site should still show a provider only after real acceptance rather than promise citywide arrival.",
    ],
    searchIntent: "Buffalo has strong city-level locksmith demand and should launch as a dedicated New York State hub.",
    marketSignals: { keyword: "locksmith buffalo ny", monthlySearches: 720, cpc: 4.76 },
  },
  {
    slug: "rochester-ny",
    name: "Rochester",
    shortLocation: "Rochester, NY",
    kind: "city",
    parent: null,
    areas: ["Park Avenue", "South Wedge", "Corn Hill", "Neighborhood of the Arts", "East Avenue", "Public Market", "19th Ward", "Downtown"],
    nearby: ["buffalo-ny", "syracuse-ny", "albany-ny"],
    localContext: "Rochester's city planning materials identify distinct neighborhoods around the Center City including Park Avenue, South Wedge, Corn Hill, the Public Market and the Neighborhood of the Arts. Housing ranges from older single- and multifamily homes to apartment buildings and downtown residential properties.",
    accessNotes: [
      "South Wedge's South Avenue functions as a neighborhood main street, while Park Avenue and East Avenue have different mixes of houses, apartments and local businesses.",
      "Corn Hill and older residential districts can involve historic doors and hardware, while downtown apartments may add managed-building access.",
      "Rochester's high locksmith CPC indicates meaningful commercial intent, making price clarity and a truthful acceptance workflow particularly important.",
    ],
    searchIntent: "Rochester is one of the strongest non-NYC New York markets in the current keyword research.",
    marketSignals: { keyword: "locksmith rochester ny", monthlySearches: 720, cpc: 17.72 },
  },
  {
    slug: "albany-ny",
    name: "Albany",
    shortLocation: "Albany, NY",
    kind: "city",
    parent: null,
    areas: ["Center Square", "Pine Hills", "Arbor Hill", "Buckingham Lake", "South End", "Delaware Area", "New Scotland", "Downtown"],
    nearby: ["schenectady-ny", "syracuse-ny", "poughkeepsie-ny"],
    localContext: "Albany's official neighborhood resources identify very different local housing environments: historic rowhouses around Center Square, student and family housing in Pine Hills, older urban fabric in Arbor Hill and the South End, and more single-family residential streets around Buckingham Lake and New Scotland.",
    accessNotes: [
      "Center Square-Hudson Park contains a large concentration of two-to-four-story brick rowhouses and mixed-use buildings around Lark Street.",
      "Pine Hills combines long-standing homeowners, renters and students, making both urgent lockouts and planned rekeys relevant.",
      "Albany's neighborhood differences support a city hub with local context rather than a generic statewide locksmith page.",
    ],
    searchIntent: "Albany has substantial city-level demand and is a first-wave Upstate New York market.",
    marketSignals: { keyword: "locksmith albany ny", monthlySearches: 720, cpc: 6.24 },
  },
  {
    slug: "syracuse-ny",
    name: "Syracuse",
    shortLocation: "Syracuse, NY",
    kind: "city",
    parent: null,
    areas: ["Downtown", "University Hill", "Eastwood", "Tipp Hill", "Salt Springs", "Elmwood", "Court-Woodlawn", "Northside"],
    nearby: ["rochester-ny", "albany-ny", "schenectady-ny"],
    localContext: "Syracuse contains compact urban neighborhoods, university-area housing and lower-density residential districts. Current city housing strategy work specifically names areas including Tipp Hill, Salt Springs, Eastwood, Elmwood and Court-Woodlawn.",
    accessNotes: [
      "University Hill has a concentrated rental and institutional environment where apartment access and tenant turnover are common contexts.",
      "Eastwood, Tipp Hill and other residential neighborhoods include many house and multifamily access situations distinct from downtown buildings.",
      "Snow and cold can increase lockout urgency, but coverage and ETA must still be based on a real provider acceptance.",
    ],
    searchIntent: "Syracuse has enough local search demand for a dedicated city page in the first New York wave.",
    marketSignals: { keyword: "locksmith syracuse ny", monthlySearches: 390, cpc: 9.32 },
  },
  {
    slug: "yonkers-ny",
    name: "Yonkers",
    shortLocation: "Yonkers, NY",
    kind: "city",
    parent: null,
    areas: ["Getty Square", "Waterfront", "Ludlow", "Park Hill", "Crestwood", "Northeast Yonkers", "McLean Avenue", "South Broadway"],
    nearby: ["bronx-ny", "white-plains-ny", "new-rochelle-ny", "new-york-ny"],
    localContext: "Yonkers stretches from dense apartment and mixed-use areas near Getty Square and South Broadway to lower-density residential neighborhoods farther east and north. The city's Hudson River edge and its direct border with the Bronx also make it part of the broader NYC/Westchester service geography.",
    accessNotes: [
      "Getty Square, South Broadway and the waterfront include denser multifamily and mixed-use buildings, while Crestwood and northeastern areas have more house-based access.",
      "Yonkers' hills, parkways and north-south corridors can make provider service areas highly address-dependent.",
      "Search CPC is high enough that a price-first page can differentiate from low-headline quote tactics.",
    ],
    searchIntent: "Yonkers is the strongest Westchester-area city query in the current research and belongs in Wave 1.",
    marketSignals: { keyword: "locksmith yonkers ny", monthlySearches: 260, cpc: 16.46 },
  },
  {
    slug: "suffolk-county-ny",
    name: "Suffolk County",
    shortLocation: "Suffolk County, Long Island",
    kind: "county",
    parent: null,
    areas: ["Huntington", "Babylon", "Islip", "Smithtown", "Brookhaven", "Patchogue", "Riverhead", "Southampton"],
    nearby: ["nassau-county-ny", "queens-ny", "new-york-ny"],
    localContext: "Suffolk County covers a very large portion of Long Island, from dense suburban communities in the west to more spread-out towns and villages farther east. Most locksmith matching therefore has to be ZIP- and address-specific rather than treating 'Suffolk County' as one practical dispatch zone.",
    accessNotes: [
      "Western Suffolk communities around Huntington, Babylon, Islip and Smithtown are much closer together than eastern parts of Brookhaven, Riverhead and the South Fork.",
      "Single-family homes are a major access context, but apartments, condos, townhouses and mixed-use village centers also create residential lock needs.",
      "Because travel distances can be substantial, provider acceptance and service-area fit should be explicit before an ETA is shown.",
    ],
    searchIntent: "Suffolk County search demand is much stronger than the generic 'Long Island locksmith' query, so the county deserves a first-wave hub.",
    marketSignals: { keyword: "locksmith suffolk county", monthlySearches: 480, cpc: 9.97 },
  },
  {
    slug: "nassau-county-ny",
    name: "Nassau County",
    shortLocation: "Nassau County, Long Island",
    kind: "county",
    parent: null,
    areas: ["Hempstead", "Garden City", "Hicksville", "Levittown", "Great Neck", "Long Beach", "Massapequa", "Mineola"],
    nearby: ["queens-ny", "suffolk-county-ny", "new-york-ny"],
    localContext: "Nassau County sits immediately east of Queens and contains dense villages, suburban single-family neighborhoods, condos, co-ops, apartments and commercial centers. Its locksmith market is therefore tied closely to specific towns and ZIP codes rather than one countywide building pattern.",
    accessNotes: [
      "Hempstead, Mineola, Hicksville and Garden City have different mixtures of apartments, houses and commercial property.",
      "Communities near the Queens border can overlap with NYC provider service areas, while farther-east Nassau needs a different matching radius.",
      "Home lockouts, rekeys and standard lock changes fit the suburban housing mix; vehicle service remains entry-only under the current scope.",
    ],
    searchIntent: "Nassau County has a clear county-level query and complements the stronger Suffolk County hub.",
    marketSignals: { keyword: "locksmith nassau county ny", monthlySearches: 140, cpc: 8.88 },
  },
  {
    slug: "white-plains-ny",
    name: "White Plains",
    shortLocation: "White Plains, NY",
    kind: "city",
    parent: null,
    areas: ["Downtown", "Battle Hill", "Highlands", "Fisher Hill", "Gedney Farms", "North Broadway", "Carhart", "Eastview"],
    nearby: ["yonkers-ny", "new-rochelle-ny", "new-york-ny"],
    localContext: "White Plains combines a substantial downtown residential core with established suburban neighborhoods. The city describes itself as having urban amenities and a growing downtown residential component while neighborhoods such as Battle Hill, Highlands and Fisher Hill retain more traditional residential patterns.",
    accessNotes: [
      "Downtown has apartment and condominium development alongside offices, retail and government buildings, so residential access can sit inside a very urban environment.",
      "Battle Hill includes predominantly single- and two-family homes plus some low-rise multifamily buildings, according to the city's current planning documents.",
      "Outside downtown, neighborhoods such as Gedney Farms, Highlands and North Broadway create more house-based rekey and lock-change contexts.",
    ],
    searchIntent: "White Plains is a useful Westchester hub with distinct urban/suburban access patterns.",
    marketSignals: { keyword: "locksmith white plains ny", monthlySearches: 140, cpc: 7.58 },
  },
  {
    slug: "poughkeepsie-ny",
    name: "Poughkeepsie",
    shortLocation: "Poughkeepsie, NY",
    kind: "city",
    parent: null,
    areas: ["Downtown", "Main Street", "Southside", "Waterfront", "Academy Street", "Hooker Avenue", "College Hill"],
    nearby: ["white-plains-ny", "albany-ny", "yonkers-ny"],
    localContext: "The City of Poughkeepsie has a compact Hudson River urban core with a wide range of residential zoning—from urban-density and multifamily districts to lower-density residential streets—plus a downtown/Main Street commercial center and waterfront area.",
    accessNotes: [
      "Main Street and the central city have mixed commercial and residential buildings, while Southside and other residential sections include older houses and multifamily properties.",
      "The city's zoning map distinguishes high-, medium- and low-density residential districts, reflecting a varied building mix within a relatively small geography.",
      "Planned rekeys and lock changes can be as relevant as urgent lockouts in owner-occupied and multifamily properties.",
    ],
    searchIntent: "Poughkeepsie has enough search demand and commercial value to justify a first-wave Hudson Valley page.",
    marketSignals: { keyword: "locksmith poughkeepsie", monthlySearches: 140, cpc: 12.93 },
  },
  {
    slug: "new-rochelle-ny",
    name: "New Rochelle",
    shortLocation: "New Rochelle, NY",
    kind: "city",
    parent: null,
    areas: ["Downtown", "Wykagyl", "North End", "Residence Park", "Rochelle Heights", "Davenport Neck", "Waterfront"],
    nearby: ["yonkers-ny", "white-plains-ny", "bronx-ny", "new-york-ny"],
    localContext: "New Rochelle combines a growing downtown with older apartment buildings, new residential towers, multifamily and single-family homes, historic neighborhoods and Long Island Sound waterfront areas. The city's own profile emphasizes this unusually broad housing mix.",
    accessNotes: [
      "Downtown includes newer condominium/residential towers, live-work lofts and older apartment buildings.",
      "North End and Wykagyl areas have more house-based residential access, while waterfront sections add another distinct property pattern.",
      "Because the city sits close to the Bronx and other Westchester markets, provider service areas should determine matching rather than assumed regional coverage.",
    ],
    searchIntent: "New Rochelle's CPC and local search volume make it a worthwhile Westchester Wave 1 page.",
    marketSignals: { keyword: "locksmith new rochelle ny", monthlySearches: 110, cpc: 14.33 },
  },
  {
    slug: "schenectady-ny",
    name: "Schenectady",
    shortLocation: "Schenectady, NY",
    kind: "city",
    parent: null,
    areas: ["Stockade", "Union Street", "Bellevue", "Mont Pleasant", "Northside", "Woodlawn", "Downtown", "Vale and Hill"],
    nearby: ["albany-ny", "syracuse-ny", "poughkeepsie-ny"],
    localContext: "Schenectady's official community profile separates neighborhoods including the historic Stockade, Union Street, Bellevue, Mont Pleasant, Northside, Woodlawn and Downtown. That local structure supports a mix of older urban housing, multifamily properties and lower-density residential blocks.",
    accessNotes: [
      "The Stockade and Union Street areas include older and historic building stock where door and cylinder conditions can differ from newer residential hardware.",
      "Mont Pleasant, Bellevue, Northside and Woodlawn represent large residential areas with many house and multifamily access situations.",
      "Albany and Schenectady are close regional markets, but provider service areas and actual acceptance should determine whether a request can be served.",
    ],
    searchIntent: "Schenectady completes the first-wave Capital Region coverage alongside Albany.",
    marketSignals: { keyword: "locksmith schenectady ny", monthlySearches: 110, cpc: 6.22 },
  },
];

export function getNyArea(slug: string) {
  return NY_AREAS.find((area) => area.slug === slug);
}

export function getNyChildren(slug: string) {
  return NY_AREAS.filter((area) => area.parent === slug);
}

export const NY_LOCAL_ROUTES = NY_AREAS.map((area) => `/${area.slug}`);
export const NY_LOCAL_PAGE_COUNT = NY_LOCAL_ROUTES.length;
