export type NortheastAreaGroup = "new-jersey" | "philadelphia" | "connecticut" | "delaware";
export type NortheastAreaKind = "city" | "township" | "neighborhood";

export type NortheastArea = {
  slug: string;
  name: string;
  shortLocation: string;
  state: "New Jersey" | "Pennsylvania" | "Connecticut" | "Delaware";
  group: NortheastAreaGroup;
  kind: NortheastAreaKind;
  parent: string | null;
  areas: string[];
  nearby: string[];
  localContext: string;
  accessNotes: string[];
  propertyTags: Array<"property-management" | "real-estate" | "second-homes">;
};

export const NORTHEAST_AREAS: NortheastArea[] = [
  {
    "slug": "jersey-city-nj",
    "name": "Jersey City",
    "shortLocation": "Jersey City, New Jersey",
    "state": "New Jersey",
    "group": "new-jersey",
    "kind": "city",
    "parent": null,
    "areas": ["Downtown Jersey City","Journal Square","The Heights","Bergen-Lafayette","Greenville","West Side"],
    "nearby": ["hoboken-nj","bayonne-nj","newark-nj","north-bergen-nj"],
    "localContext": "Jersey City combines high-rise waterfront apartments, brownstones, multifamily houses and older walk-ups across distinct neighborhoods from Downtown and Journal Square to the Heights, Bergen-Lafayette, Greenville and the West Side.",
    "accessNotes": ["A unit lockout in a waterfront tower can involve lobby or building-management access before the apartment door itself.","Journal Square, Kennedy Boulevard, Newark Avenue and Route 440 create very different arrival and parking conditions across the city.","Rekeys and lock changes are especially relevant after moves, tenant turnover or changes in who should hold keys to a multifamily property."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "newark-nj",
    "name": "Newark",
    "shortLocation": "Newark, New Jersey",
    "state": "New Jersey",
    "group": "new-jersey",
    "kind": "city",
    "parent": null,
    "areas": ["Downtown Newark","Ironbound","University Heights","North Ward","South Ward","Weequahic"],
    "nearby": ["jersey-city-nj","elizabeth-nj","union-nj","clifton-nj"],
    "localContext": "Newark spans dense apartment corridors, rowhouses, multifamily homes and mixed-use districts, with very different access patterns between Downtown, the Ironbound, University Heights, the North Ward, South Ward and Weequahic.",
    "accessNotes": ["Downtown and University Heights can add controlled-building or institutional access layers to a unit-level lock problem.","Broad Street, Springfield Avenue, Ferry Street and McCarter Highway shape local travel and can make exact-address matching more useful than a citywide ETA.","Residential rekeys and lock changes often follow tenant turnover, ownership changes or lost-key concerns in multifamily properties."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "toms-river-nj",
    "name": "Toms River",
    "shortLocation": "Toms River, New Jersey",
    "state": "New Jersey",
    "group": "new-jersey",
    "kind": "city",
    "parent": null,
    "areas": ["Downtown Toms River","Silverton","East Dover","North Dover","Hooper Avenue","Route 37"],
    "nearby": ["atlantic-city-nj","hamilton-nj","cherry-hill-nj"],
    "localContext": "Toms River is a spread-out residential market with detached homes, townhouses, condo communities and commercial corridors around Hooper Avenue and Route 37 rather than one dense downtown access pattern.",
    "accessNotes": ["Provider service radius matters because requests can be separated by long local drives even within the township.","Detached homes and condo communities create different rekey and lock-change scopes from apartment buildings.","Route 37 and Hooper Avenue are important local corridors, so the exact address should determine matching rather than a generic township-wide promise."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "edison-nj",
    "name": "Edison",
    "shortLocation": "Edison, New Jersey",
    "state": "New Jersey",
    "group": "new-jersey",
    "kind": "city",
    "parent": null,
    "areas": ["Menlo Park","Clara Barton","Oak Tree","Stelton","New Durham","Route 1 corridor"],
    "nearby": ["new-brunswick-nj","north-brunswick-nj","union-nj","jersey-city-nj"],
    "localContext": "Edison is a large suburban township with detached homes, townhouses, apartment communities and major employment and retail corridors around Route 1, Oak Tree Road and the Menlo Park area.",
    "accessNotes": ["The township's size makes provider coverage and travel distance more important than a single Edison-wide ETA.","Move-in rekeys and smart-lock installations fit the housing mix of detached homes, townhouses and condo communities.","Route 1, Route 27 and Oak Tree Road divide very different residential and commercial pockets, so exact service location matters."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "hackensack-nj",
    "name": "Hackensack",
    "shortLocation": "Hackensack, New Jersey",
    "state": "New Jersey",
    "group": "new-jersey",
    "kind": "city",
    "parent": null,
    "areas": ["Main Street","Fairmount","Prospect Avenue","River Street","Anderson Street","Essex Street"],
    "nearby": ["teaneck-nj","north-bergen-nj","jersey-city-nj","clifton-nj"],
    "localContext": "Hackensack mixes apartment towers and mid-rise buildings around Prospect Avenue with older houses, multifamily properties and a compact Main Street downtown.",
    "accessNotes": ["Apartment-heavy corridors can add lobby, management or common-entry considerations before a locksmith reaches the private unit.","Main Street, River Street, Essex Street and Route 4 access shape how providers approach different parts of the city.","Planned rekeys and lock changes are relevant for rentals and multifamily properties as well as owner-occupied homes."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "teaneck-nj",
    "name": "Teaneck",
    "shortLocation": "Teaneck, New Jersey",
    "state": "New Jersey",
    "group": "new-jersey",
    "kind": "city",
    "parent": null,
    "areas": ["Cedar Lane","West Englewood","Queen Anne Road","Teaneck Road","DeGraw Avenue","Route 4 corridor"],
    "nearby": ["hackensack-nj","north-bergen-nj","jersey-city-nj","clifton-nj"],
    "localContext": "Teaneck is primarily residential, with detached homes, two-family properties, apartment buildings and neighborhood commercial corridors centered on Cedar Lane, Queen Anne Road and Teaneck Road.",
    "accessNotes": ["Residential lock work is often house-based, but apartment and multifamily addresses can involve shared-entry considerations.","Route 4 can divide provider approach patterns from local street access, making exact-address routing useful.","Rekeys after moving, changing tenants or losing control of old keys are a natural fit for Teaneck's residential mix."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "elizabeth-nj",
    "name": "Elizabeth",
    "shortLocation": "Elizabeth, New Jersey",
    "state": "New Jersey",
    "group": "new-jersey",
    "kind": "city",
    "parent": null,
    "areas": ["Elmora","Peterstown","North End","Elizabethport","Midtown","Bayway"],
    "nearby": ["newark-nj","union-nj","jersey-city-nj","bayonne-nj"],
    "localContext": "Elizabeth combines dense multifamily neighborhoods, rowhouses, apartments and detached homes across Elmora, Peterstown, the North End, Elizabethport, Midtown and Bayway.",
    "accessNotes": ["Multifamily and apartment requests should distinguish private-unit access from common building entry.","Broad Street, Elmora Avenue, Elizabeth Avenue and Routes 1&9 create different local access and travel patterns.","Tenant turnover and key-control changes make rekeying a recurring property-management use case in multifamily housing."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "clifton-nj",
    "name": "Clifton",
    "shortLocation": "Clifton, New Jersey",
    "state": "New Jersey",
    "group": "new-jersey",
    "kind": "city",
    "parent": null,
    "areas": ["Allwood","Athenia","Botany Village","Delawanna","Dutch Hill","Lakeview"],
    "nearby": ["paterson-nj","newark-nj","hackensack-nj","union-nj"],
    "localContext": "Clifton is a patchwork of residential neighborhoods such as Allwood, Athenia, Botany Village, Delawanna, Dutch Hill and Lakeview, with a mix of detached homes, multifamily properties and apartment buildings.",
    "accessNotes": ["Route 3, Route 46 and local roads can make two Clifton addresses operationally very different for a provider.","Older multifamily homes and detached houses can have different cylinder and lock-change requirements.","A local request should carry the exact neighborhood and address rather than rely on a blanket Clifton service promise."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "trenton-nj",
    "name": "Trenton",
    "shortLocation": "Trenton, New Jersey",
    "state": "New Jersey",
    "group": "new-jersey",
    "kind": "city",
    "parent": null,
    "areas": ["Chambersburg","Mill Hill","Hiltonia","Berkeley Square","North Trenton","Wilbur"],
    "nearby": ["hamilton-nj","new-brunswick-nj","cherry-hill-nj"],
    "localContext": "Trenton's housing includes rowhouses, twins, detached homes and apartment buildings across neighborhoods such as Chambersburg, Mill Hill, Hiltonia, Berkeley Square, North Trenton and Wilbur.",
    "accessNotes": ["Older rowhouse blocks can present different lock hardware from detached homes and newer apartment properties.","State Street, Broad Street, Route 1 and neighborhood street grids create distinct access patterns across the city.","Rekeys and lock changes are particularly relevant when occupancy or key possession changes in rental and owner-occupied properties."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "north-bergen-nj",
    "name": "North Bergen",
    "shortLocation": "North Bergen, New Jersey",
    "state": "New Jersey",
    "group": "new-jersey",
    "kind": "city",
    "parent": null,
    "areas": ["Bergenline Avenue","Kennedy Boulevard","Bulls Ferry","Woodcliff","Broadway","River Road"],
    "nearby": ["jersey-city-nj","hoboken-nj","hackensack-nj","teaneck-nj"],
    "localContext": "North Bergen combines dense apartment and multifamily corridors along Bergenline Avenue and Kennedy Boulevard with newer riverfront housing around Bulls Ferry and River Road.",
    "accessNotes": ["Steep local grades, dense parking and riverfront versus inland access can change how a provider reaches the property.","Apartment requests should identify whether the issue is the unit door or a common building entrance.","Rekey and lock-change work is relevant for both rental turnover and owner-occupied condos or multifamily properties."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "hamilton-nj",
    "name": "Hamilton Township",
    "shortLocation": "Hamilton Township, New Jersey",
    "state": "New Jersey",
    "group": "new-jersey",
    "kind": "township",
    "parent": null,
    "areas": ["Hamilton Square","Mercerville","Yardville","White Horse","Groveville","Route 33 corridor"],
    "nearby": ["trenton-nj","new-brunswick-nj","cherry-hill-nj","toms-river-nj"],
    "localContext": "Hamilton Township is a broad suburban market with detached homes, townhouses, apartment communities and older village centers around Hamilton Square, Mercerville, Yardville, White Horse and Groveville.",
    "accessNotes": ["The township's size makes service-area matching important; two Hamilton addresses can be separated by substantial local travel.","Route 33, Route 130 and I-295 shape provider access differently from neighborhood streets.","Move-in rekeys and smart-lock installation fit owner-occupied homes and townhouse communities especially well."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "cherry-hill-nj",
    "name": "Cherry Hill",
    "shortLocation": "Cherry Hill, New Jersey",
    "state": "New Jersey",
    "group": "new-jersey",
    "kind": "city",
    "parent": null,
    "areas": ["Erlton","Barclay","Kingston","Ashland","Haddonfield Road","Route 70 corridor"],
    "nearby": ["philadelphia-pa","hamilton-nj","atlantic-city-nj","toms-river-nj"],
    "localContext": "Cherry Hill is a suburban residential and retail market with detached homes, townhouses, apartment communities and neighborhoods such as Erlton, Barclay, Kingston and Ashland.",
    "accessNotes": ["Route 70, Route 38 and Haddonfield Road create distinct provider approach patterns across the township.","Detached homes and townhouses make planned rekeys, lock changes and smart-lock installations prominent use cases alongside urgent lockouts.","The exact address is necessary because neighborhood streets and large commercial corridors create different parking and access conditions."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "new-brunswick-nj",
    "name": "New Brunswick",
    "shortLocation": "New Brunswick, New Jersey",
    "state": "New Jersey",
    "group": "new-jersey",
    "kind": "city",
    "parent": null,
    "areas": ["College Avenue","George Street","French Street","Livingston Avenue","Feaster Park","Rutgers area"],
    "nearby": ["north-brunswick-nj","edison-nj","trenton-nj","union-nj"],
    "localContext": "New Brunswick mixes university housing, apartment buildings, older multifamily homes and dense residential blocks around College Avenue, George Street, French Street and Livingston Avenue.",
    "accessNotes": ["Student and rental turnover can create recurring rekey needs where control of old keys is uncertain.","Downtown and Rutgers-area buildings may add common-entry or management access layers to a unit-level lockout.","Route 18, George Street and the rail corridor shape local provider access, so address-specific matching is important."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "north-brunswick-nj",
    "name": "North Brunswick",
    "shortLocation": "North Brunswick, New Jersey",
    "state": "New Jersey",
    "group": "new-jersey",
    "kind": "city",
    "parent": null,
    "areas": ["Berdines Corner","Adams","Georges Road","Livingston Avenue","Route 1 corridor","Route 130 corridor"],
    "nearby": ["new-brunswick-nj","edison-nj","hamilton-nj","trenton-nj"],
    "localContext": "North Brunswick combines suburban neighborhoods, townhouse and apartment communities and major commercial corridors along Route 1, Route 130, Georges Road and Livingston Avenue.",
    "accessNotes": ["Provider travel can vary significantly between residential pockets and the Route 1/130 corridors.","Rekeys and lock changes are common planned access tasks for moves, tenant changes and lost-key concerns.","Exact service location matters more than a township-wide arrival estimate because the market is geographically spread out."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "paterson-nj",
    "name": "Paterson",
    "shortLocation": "Paterson, New Jersey",
    "state": "New Jersey",
    "group": "new-jersey",
    "kind": "city",
    "parent": null,
    "areas": ["Downtown Paterson","Eastside","South Paterson","Hillcrest","Riverside","Totowa section"],
    "nearby": ["clifton-nj","hackensack-nj","newark-nj","morristown-nj"],
    "localContext": "Paterson includes dense multifamily housing, rowhouses, apartment buildings and detached homes across Downtown, Eastside, South Paterson, Hillcrest, Riverside and the Totowa section.",
    "accessNotes": ["Apartment and multifamily requests should distinguish unit-door access from shared-building entry.","Main Street, Market Street, Broadway and Route 20 create different access patterns across neighborhoods.","Rental turnover and changes in key possession make rekeying a recurring use case for local landlords and property managers."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "hoboken-nj",
    "name": "Hoboken",
    "shortLocation": "Hoboken, New Jersey",
    "state": "New Jersey",
    "group": "new-jersey",
    "kind": "city",
    "parent": null,
    "areas": ["Washington Street","Waterfront","Uptown","Downtown","Northwest","Southwest"],
    "nearby": ["jersey-city-nj","north-bergen-nj","bayonne-nj","hackensack-nj"],
    "localContext": "Hoboken is a compact, apartment-heavy city with brownstones, walk-ups, condo buildings and newer waterfront towers concentrated around Washington Street and the Hudson waterfront.",
    "accessNotes": ["A private-unit lockout can be separate from lobby, doorman or common-entry access in larger buildings.","Dense curb use and limited parking make precise address and real provider acceptance more credible than a generic ETA.","High residential turnover in rentals and condos makes rekeys and lock changes relevant after moves or key-control changes."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "bayonne-nj",
    "name": "Bayonne",
    "shortLocation": "Bayonne, New Jersey",
    "state": "New Jersey",
    "group": "new-jersey",
    "kind": "city",
    "parent": null,
    "areas": ["Bergen Point","Constable Hook","Midtown","Broadway","Avenue C","North Bayonne"],
    "nearby": ["jersey-city-nj","elizabeth-nj","hoboken-nj","newark-nj"],
    "localContext": "Bayonne is a linear peninsula city with rowhouses, two-family homes, detached houses and apartment buildings stretching from Bergen Point through Midtown to North Bayonne.",
    "accessNotes": ["Broadway and Avenue C run through long residential stretches, so provider distance can vary materially within the city.","Two-family and multifamily housing creates recurring rekey needs after tenant or key-holder changes.","Waterfront redevelopment and older residential blocks can present very different building-entry and hardware contexts."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "morristown-nj",
    "name": "Morristown",
    "shortLocation": "Morristown, New Jersey",
    "state": "New Jersey",
    "group": "new-jersey",
    "kind": "city",
    "parent": null,
    "areas": ["The Green","South Street","Washington Street","Speedwell Avenue","Morris Street","Franklin Street"],
    "nearby": ["union-nj","paterson-nj","new-brunswick-nj","edison-nj"],
    "localContext": "Morristown combines apartments and condos around the downtown core with older houses, townhouses and residential streets radiating from the Green, South Street, Washington Street and Speedwell Avenue.",
    "accessNotes": ["Downtown apartments can involve common-building access while nearby houses create straightforward private-entry requests.","The Green, South Street and Speedwell Avenue concentrate activity and can affect curb access during busy periods.","Move-in rekeys, lock changes and smart-lock installations fit both downtown residential units and owner-occupied homes."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "union-nj",
    "name": "Union Township",
    "shortLocation": "Union Township, New Jersey",
    "state": "New Jersey",
    "group": "new-jersey",
    "kind": "township",
    "parent": null,
    "areas": ["Union Center","Five Points","Battle Hill","Vauxhall","Morris Avenue","Stuyvesant Avenue"],
    "nearby": ["newark-nj","elizabeth-nj","morristown-nj","edison-nj"],
    "localContext": "Union Township combines detached homes, multifamily properties, apartment communities and neighborhood centers around Union Center, Five Points, Battle Hill, Vauxhall, Morris Avenue and Stuyvesant Avenue.",
    "accessNotes": ["Route 22, Morris Avenue and local residential streets create different provider travel patterns across the township.","Owner moves and tenant turnover make rekeying a common planned security task.","Exact service address is important because the township includes both dense corridors and quieter residential pockets."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "atlantic-city-nj",
    "name": "Atlantic City",
    "shortLocation": "Atlantic City, New Jersey",
    "state": "New Jersey",
    "group": "new-jersey",
    "kind": "city",
    "parent": null,
    "areas": ["Boardwalk","Marina District","Chelsea","Ducktown","Bungalow Park","Venice Park"],
    "nearby": ["toms-river-nj","cherry-hill-nj","philadelphia-pa"],
    "localContext": "Atlantic City mixes high-rise residential and hospitality buildings with rowhouses, small multifamily properties and neighborhood streets across Chelsea, Ducktown, Bungalow Park, Venice Park, the Boardwalk and Marina District.",
    "accessNotes": ["Large buildings can add security-desk, management or common-entry layers before a locksmith reaches a private unit.","Seasonal visitor traffic and event activity can affect curb access and travel time around the Boardwalk and Marina District.","Residential rekeys and lock changes should remain distinct from hotel or casino commercial-security work outside the current standard scope."],
    "propertyTags": ["property-management","real-estate","second-homes"]
  },
  {
    "slug": "philadelphia-pa",
    "name": "Philadelphia",
    "shortLocation": "Philadelphia, Pennsylvania",
    "state": "Pennsylvania",
    "group": "philadelphia",
    "kind": "city",
    "parent": null,
    "areas": ["Center City","Northeast Philadelphia","West Philadelphia","South Philadelphia","North Philadelphia","Fishtown","Manayunk"],
    "nearby": ["center-city-philadelphia-pa","northeast-philadelphia-pa","west-philadelphia-pa","south-philadelphia-pa","north-philadelphia-pa","fishtown-philadelphia-pa","manayunk-philadelphia-pa","cherry-hill-nj"],
    "localContext": "Philadelphia is a collection of distinct residential markets: dense Center City apartments, rowhouse neighborhoods across North and South Philadelphia, university-area rentals in West Philadelphia, lower-density Northeast sections and hillside rowhomes around Manayunk.",
    "accessNotes": ["Philadelphia's planning framework divides the city into 18 planning districts, reinforcing the need to route by neighborhood and exact address rather than use one citywide access assumption.","Rowhouses, converted multifamily buildings, apartment towers and detached homes can require very different rekey or lock-change scopes.","Parking, one-way streets and neighborhood-specific travel patterns make a real provider acceptance more useful than a blanket citywide ETA."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "northeast-philadelphia-pa",
    "name": "Northeast Philadelphia",
    "shortLocation": "Northeast Philadelphia, Pennsylvania",
    "state": "Pennsylvania",
    "group": "philadelphia",
    "kind": "neighborhood",
    "parent": "philadelphia-pa",
    "areas": ["Mayfair","Tacony","Holmesburg","Rhawnhurst","Bustleton","Somerton","Torresdale"],
    "nearby": ["philadelphia-pa","north-philadelphia-pa","fishtown-philadelphia-pa","cherry-hill-nj"],
    "localContext": "Northeast Philadelphia spans rowhouse blocks, twins, detached homes, apartment communities and commercial corridors across Mayfair, Tacony, Holmesburg, Rhawnhurst, Bustleton, Somerton and Torresdale.",
    "accessNotes": ["The Northeast covers a large area, so provider service radius and the exact ZIP/address matter more than a generic Philadelphia ETA.","Roosevelt Boulevard, Frankford Avenue, Bustleton Avenue and Cottman Avenue create different travel and parking conditions across submarkets.","Rekeys, lock changes and smart-lock installation fit the area's large stock of owner-occupied houses and rentals."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "west-philadelphia-pa",
    "name": "West Philadelphia",
    "shortLocation": "West Philadelphia, Pennsylvania",
    "state": "Pennsylvania",
    "group": "philadelphia",
    "kind": "neighborhood",
    "parent": "philadelphia-pa",
    "areas": ["University City","Spruce Hill","Walnut Hill","Cobbs Creek","Haddington","Overbrook"],
    "nearby": ["philadelphia-pa","center-city-philadelphia-pa","north-philadelphia-pa","south-philadelphia-pa"],
    "localContext": "West Philadelphia mixes university-area apartments and converted rowhouses with long-established residential neighborhoods such as Spruce Hill, Walnut Hill, Cobbs Creek, Haddington and Overbrook.",
    "accessNotes": ["Student and rental turnover around University City can create recurring rekey needs.","Market Street, Lancaster Avenue, Baltimore Avenue and major transit corridors shape provider access between neighborhoods.","A unit lockout in a larger apartment building can involve common-entry or property-management access before private-door work."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "south-philadelphia-pa",
    "name": "South Philadelphia",
    "shortLocation": "South Philadelphia, Pennsylvania",
    "state": "Pennsylvania",
    "group": "philadelphia",
    "kind": "neighborhood",
    "parent": "philadelphia-pa",
    "areas": ["Passyunk Square","East Passyunk","Point Breeze","Graduate Hospital","Bella Vista","Queen Village"],
    "nearby": ["philadelphia-pa","center-city-philadelphia-pa","west-philadelphia-pa","fishtown-philadelphia-pa"],
    "localContext": "South Philadelphia is dominated by compact rowhouse blocks, mixed-use avenues and newer infill housing across Passyunk Square, East Passyunk, Point Breeze, Graduate Hospital, Bella Vista and Queen Village.",
    "accessNotes": ["Narrow rowhouse streets and dense curb parking can affect provider access even when distances are short.","Broad Street, Passyunk Avenue, Washington Avenue and Columbus Boulevard connect very different residential pockets.","Rekeys and lock changes are especially relevant after home purchases, tenant changes or lost-key concerns in rowhouses and converted multifamily properties."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "center-city-philadelphia-pa",
    "name": "Center City",
    "shortLocation": "Center City Philadelphia, Pennsylvania",
    "state": "Pennsylvania",
    "group": "philadelphia",
    "kind": "neighborhood",
    "parent": "philadelphia-pa",
    "areas": ["Rittenhouse Square","Washington Square West","Logan Square","Society Hill","Market East","Old City"],
    "nearby": ["philadelphia-pa","west-philadelphia-pa","south-philadelphia-pa","fishtown-philadelphia-pa"],
    "localContext": "Center City combines high-rise apartments and condos with historic rowhouses, converted buildings and mixed-use blocks across Rittenhouse Square, Washington Square West, Logan Square, Society Hill, Market East and Old City.",
    "accessNotes": ["High-rise residences can involve front-desk, elevator or building-management access before unit-door service.","One-way streets, loading zones and dense curb demand make exact-address routing important.","Move-in rekeys and smart-lock installations are relevant for condos and rowhouses, while building-wide access-control systems remain outside the current standard residential scope."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "fishtown-philadelphia-pa",
    "name": "Fishtown",
    "shortLocation": "Fishtown, Philadelphia",
    "state": "Pennsylvania",
    "group": "philadelphia",
    "kind": "neighborhood",
    "parent": "philadelphia-pa",
    "areas": ["Frankford Avenue","Girard Avenue","Front Street","Norris Street","Palmer Street","Penn Treaty area"],
    "nearby": ["philadelphia-pa","center-city-philadelphia-pa","north-philadelphia-pa","northeast-philadelphia-pa"],
    "localContext": "Fishtown mixes classic Philadelphia rowhouses with converted industrial buildings, newer apartments and mixed-use corridors concentrated around Frankford Avenue, Girard Avenue and Front Street.",
    "accessNotes": ["Rowhouse doors and newer apartment-unit doors can involve very different hardware and building-entry conditions.","Frankford Avenue and Girard Avenue carry heavy neighborhood activity, so curb access can vary block by block.","High renter and owner turnover makes planned rekeys and lock changes a natural move-in and property-management use case."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "north-philadelphia-pa",
    "name": "North Philadelphia",
    "shortLocation": "North Philadelphia, Pennsylvania",
    "state": "Pennsylvania",
    "group": "philadelphia",
    "kind": "neighborhood",
    "parent": "philadelphia-pa",
    "areas": ["Temple area","Brewerytown","Fairhill","Strawberry Mansion","Nicetown-Tioga","Francisville"],
    "nearby": ["philadelphia-pa","fishtown-philadelphia-pa","west-philadelphia-pa","northeast-philadelphia-pa"],
    "localContext": "North Philadelphia spans dense rowhouse neighborhoods, multifamily buildings, university-area rentals and redevelopment corridors around Temple, Brewerytown, Fairhill, Strawberry Mansion, Nicetown-Tioga and Francisville.",
    "accessNotes": ["Rental and student turnover can create repeat rekey demand where old keys may remain in circulation.","Broad Street, Girard Avenue and North Philadelphia's rail and arterial corridors create different provider approach patterns.","Rowhouse lock work should be scoped separately from common-entry or multifamily-building access."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "manayunk-philadelphia-pa",
    "name": "Manayunk",
    "shortLocation": "Manayunk, Philadelphia",
    "state": "Pennsylvania",
    "group": "philadelphia",
    "kind": "neighborhood",
    "parent": "philadelphia-pa",
    "areas": ["Main Street","Ridge Avenue","Leverington","Wissahickon","Roxborough","Cresson Street"],
    "nearby": ["philadelphia-pa","west-philadelphia-pa","north-philadelphia-pa","center-city-philadelphia-pa"],
    "localContext": "Manayunk's steep hillside streets combine rowhouses, apartments, converted mill buildings and newer residential development around Main Street, Ridge Avenue, Cresson Street and the Schuylkill riverfront.",
    "accessNotes": ["Steep grades, narrow streets and limited curb space can affect provider access even over short distances.","Apartments and converted buildings may add common-entry considerations before unit-door work.","Move-in rekeys and smart-lock installations fit both rowhouses and newer owner-occupied units in the Manayunk/Roxborough market."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "bridgeport-ct",
    "name": "Bridgeport",
    "shortLocation": "Bridgeport, Connecticut",
    "state": "Connecticut",
    "group": "connecticut",
    "kind": "city",
    "parent": null,
    "areas": ["Black Rock","North End","South End","East Side","East End","Brooklawn","Downtown"],
    "nearby": ["fairfield-ct","stamford-ct","new-haven-ct","norwalk-ct"],
    "localContext": "Bridgeport mixes dense multifamily neighborhoods, apartment buildings and detached homes across Black Rock, the North End, South End, East Side, East End, Brooklawn and Downtown.",
    "accessNotes": ["Apartment and multifamily addresses should distinguish unit-door access from common building entry.","Main Street, Park Avenue, Boston Avenue and I-95 approaches create different provider travel patterns across neighborhoods.","Rekeys after tenant turnover or changes in key possession are a recurring property-management use case."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "hartford-ct",
    "name": "Hartford",
    "shortLocation": "Hartford, Connecticut",
    "state": "Connecticut",
    "group": "connecticut",
    "kind": "city",
    "parent": null,
    "areas": ["Downtown Hartford","West End","South End","Frog Hollow","Asylum Hill","Barry Square","Behind the Rocks"],
    "nearby": ["west-hartford-ct","new-haven-ct","waterbury-ct","stamford-ct"],
    "localContext": "Hartford includes apartment buildings, historic multifamily housing, rowhouses and detached homes across Downtown, the West End, South End, Frog Hollow, Asylum Hill, Barry Square and Behind the Rocks.",
    "accessNotes": ["Dense multifamily areas can involve shared entrances and property-management coordination in addition to a unit-door problem.","Farmington Avenue, Park Street, Albany Avenue and I-84 access shape different provider approach patterns.","Planned rekeys and lock changes are important after rental turnover, ownership changes or lost-key concerns."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "stamford-ct",
    "name": "Stamford",
    "shortLocation": "Stamford, Connecticut",
    "state": "Connecticut",
    "group": "connecticut",
    "kind": "city",
    "parent": null,
    "areas": ["Downtown Stamford","Harbor Point","Shippan","Glenbrook","Springdale","Cove","North Stamford"],
    "nearby": ["greenwich-ct","norwalk-ct","bridgeport-ct","new-york-ny"],
    "localContext": "Stamford ranges from high-rise apartments in Downtown and Harbor Point to multifamily neighborhoods in Glenbrook and Springdale, coastal housing around Shippan and the Cove, and detached homes in North Stamford.",
    "accessNotes": ["The city maintains neighborhood profiles because its districts differ materially in density and land use; exact-address matching is therefore more meaningful than a citywide promise.","I-95, the Merritt Parkway, Washington Boulevard and local neighborhood streets create very different provider access conditions.","Move-in rekeys, lock changes and smart-lock installation fit the city's mix of condos, rentals and owner-occupied homes."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "new-haven-ct",
    "name": "New Haven",
    "shortLocation": "New Haven, Connecticut",
    "state": "Connecticut",
    "group": "connecticut",
    "kind": "city",
    "parent": null,
    "areas": ["Downtown New Haven","East Rock","Westville","Wooster Square","Fair Haven","Newhallville","The Hill"],
    "nearby": ["hamden-ct","milford-ct","bridgeport-ct","hartford-ct"],
    "localContext": "New Haven combines university-area apartments, historic rowhouses, multifamily housing and detached homes across Downtown, East Rock, Westville, Wooster Square, Fair Haven, Newhallville and the Hill.",
    "accessNotes": ["Rental and student turnover can create recurring rekey needs where former occupants may still hold keys.","Whalley Avenue, Chapel Street, State Street and I-91/I-95 approaches shape different provider travel patterns.","Apartment and multifamily requests should distinguish unit access from common building entrances."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "norwalk-ct",
    "name": "Norwalk",
    "shortLocation": "Norwalk, Connecticut",
    "state": "Connecticut",
    "group": "connecticut",
    "kind": "city",
    "parent": null,
    "areas": ["South Norwalk","East Norwalk","Rowayton","Cranbury","Silvermine","West Norwalk","Wolfpit"],
    "nearby": ["stamford-ct","greenwich-ct","fairfield-ct","bridgeport-ct"],
    "localContext": "Norwalk includes dense mixed-use and apartment areas in South Norwalk alongside coastal neighborhoods, detached homes and lower-density residential areas such as Rowayton, Cranbury, Silvermine and West Norwalk.",
    "accessNotes": ["SoNo apartment and condo requests can involve common-building access before unit-door service.","I-95, Route 7, West Avenue and local coastal roads make provider travel highly address-dependent.","Second-home and property-access use cases are relevant in coastal and lower-density parts of the city as well as standard residential lockouts."],
    "propertyTags": ["property-management","real-estate","second-homes"]
  },
  {
    "slug": "waterbury-ct",
    "name": "Waterbury",
    "shortLocation": "Waterbury, Connecticut",
    "state": "Connecticut",
    "group": "connecticut",
    "kind": "city",
    "parent": null,
    "areas": ["Downtown Waterbury","Town Plot","Bunker Hill","East End","Overlook","Brooklyn","Waterville"],
    "nearby": ["hartford-ct","new-haven-ct","danbury-ct","hamden-ct"],
    "localContext": "Waterbury combines dense multifamily neighborhoods, older apartment buildings and detached homes across Downtown, Town Plot, Bunker Hill, the East End, Overlook, Brooklyn and Waterville.",
    "accessNotes": ["Older multifamily housing can involve multiple cylinders, shared entrances or landlord coordination for planned rekeys.","I-84, Route 8, East Main Street and Watertown Avenue create different provider approach patterns across the city.","Exact-address matching is important because neighborhood density and access conditions vary widely."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "fairfield-ct",
    "name": "Fairfield",
    "shortLocation": "Fairfield, Connecticut",
    "state": "Connecticut",
    "group": "connecticut",
    "kind": "city",
    "parent": null,
    "areas": ["Fairfield Center","Southport","Stratfield","Greenfield Hill","Tunxis Hill","Beach area","University area"],
    "nearby": ["bridgeport-ct","norwalk-ct","milford-ct","stamford-ct"],
    "localContext": "Fairfield is primarily residential, ranging from compact village and beach neighborhoods to larger detached homes in Greenfield Hill and suburban streets in Stratfield and Tunxis Hill.",
    "accessNotes": ["Southport and beach-area properties can have different access patterns from inland single-family neighborhoods.","Post Road, Black Rock Turnpike and I-95 approaches create different provider travel routes.","Move-in rekeys, smart-lock installs and second-home access planning fit Fairfield's owner-occupied housing market."],
    "propertyTags": ["property-management","real-estate","second-homes"]
  },
  {
    "slug": "danbury-ct",
    "name": "Danbury",
    "shortLocation": "Danbury, Connecticut",
    "state": "Connecticut",
    "group": "connecticut",
    "kind": "city",
    "parent": null,
    "areas": ["CityCenter Danbury","Germantown","Mill Plain","Great Plain","King Street","Shelter Rock","Ridgebury"],
    "nearby": ["waterbury-ct","stamford-ct","norwalk-ct","hartford-ct"],
    "localContext": "Danbury is a geographically broad market with Downtown apartments, multifamily housing and extensive suburban neighborhoods around Germantown, Mill Plain, Great Plain, King Street, Shelter Rock and Ridgebury.",
    "accessNotes": ["The city's spread means provider service radius and exact address are central to credible matching.","I-84, Route 7 and Mill Plain Road create different travel patterns from neighborhood streets.","Detached homes and condos make move-in rekeys and smart-lock installation important alongside emergency access."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "west-hartford-ct",
    "name": "West Hartford",
    "shortLocation": "West Hartford, Connecticut",
    "state": "Connecticut",
    "group": "connecticut",
    "kind": "city",
    "parent": null,
    "areas": ["West Hartford Center","Blue Back Square","Elmwood","Bishops Corner","Park Road","Fernridge"],
    "nearby": ["hartford-ct","waterbury-ct","new-haven-ct","stamford-ct"],
    "localContext": "West Hartford combines apartment and condo living around the Center and Blue Back Square with detached homes, multifamily properties and neighborhood commercial districts such as Elmwood, Bishops Corner and Park Road.",
    "accessNotes": ["Center-area apartments can involve common-entry or property-management access before private-unit service.","Farmington Avenue, Park Road and New Britain Avenue connect very different residential pockets.","Rekeys and smart-lock installs fit both rental turnover and owner move-in needs across the town."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "milford-ct",
    "name": "Milford",
    "shortLocation": "Milford, Connecticut",
    "state": "Connecticut",
    "group": "connecticut",
    "kind": "city",
    "parent": null,
    "areas": ["Downtown Milford","Devon","Woodmont","Walnut Beach","Silver Sands","Bayview","Gulf Beach"],
    "nearby": ["new-haven-ct","bridgeport-ct","fairfield-ct","hamden-ct"],
    "localContext": "Milford combines a compact downtown with suburban neighborhoods and a long shoreline, including Devon, Woodmont, Walnut Beach, Silver Sands, Bayview and Gulf Beach.",
    "accessNotes": ["Coastal and second-home access situations can be different from standard inland residential lockouts.","Boston Post Road, I-95 and shoreline streets create different provider access patterns.","Rekeys, lock changes and smart-lock installation are relevant after moves, tenant turnover or changes in trusted property access."],
    "propertyTags": ["property-management","real-estate","second-homes"]
  },
  {
    "slug": "greenwich-ct",
    "name": "Greenwich",
    "shortLocation": "Greenwich, Connecticut",
    "state": "Connecticut",
    "group": "connecticut",
    "kind": "city",
    "parent": null,
    "areas": ["Greenwich","Cos Cob","Riverside","Old Greenwich","Byram","Glenville","Backcountry"],
    "nearby": ["stamford-ct","norwalk-ct","fairfield-ct","new-york-ny"],
    "localContext": "Greenwich is a collection of distinct villages and residential areas, from denser apartment and condo locations near Greenwich Avenue to houses in Cos Cob, Riverside, Old Greenwich, Byram, Glenville and the Backcountry.",
    "accessNotes": ["Large properties and lower-density areas can make exact provider service radius especially important.","I-95, the Merritt Parkway and village road networks create very different travel routes within the town.","Second-home, estate-access, move-in rekey and smart-lock use cases are strategically important alongside urgent lockouts."],
    "propertyTags": ["property-management","real-estate","second-homes"]
  },
  {
    "slug": "hamden-ct",
    "name": "Hamden",
    "shortLocation": "Hamden, Connecticut",
    "state": "Connecticut",
    "group": "connecticut",
    "kind": "city",
    "parent": null,
    "areas": ["Whitneyville","Spring Glen","Mount Carmel","Centerville","Highwood","Hamden Plains","West Woods"],
    "nearby": ["new-haven-ct","waterbury-ct","milford-ct","hartford-ct"],
    "localContext": "Hamden stretches north from New Haven through neighborhoods such as Whitneyville, Spring Glen, Mount Carmel, Centerville, Highwood, Hamden Plains and West Woods, with apartments, multifamily properties and detached homes.",
    "accessNotes": ["Whitney Avenue is a major spine, but service locations can be widely separated along the town's north-south geography.","Rental and multifamily areas near New Haven create different rekey needs from detached homes farther north.","Exact-address matching matters because the town covers both dense southern neighborhoods and lower-density northern areas."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "wilmington-de",
    "name": "Wilmington",
    "shortLocation": "Wilmington, Delaware",
    "state": "Delaware",
    "group": "delaware",
    "kind": "city",
    "parent": null,
    "areas": ["Downtown Wilmington","Riverfront","Trolley Square","Cool Spring/Tilton Park","East Side","Browntown/Hedgeville","Baynard Boulevard"],
    "nearby": ["newark-de","middletown-de","dover-de","philadelphia-pa"],
    "localContext": "Wilmington has 42 recognized neighborhoods and a housing mix that includes downtown apartments, Riverfront developments, rowhouse districts and historic residential areas such as Trolley Square, Cool Spring/Tilton Park, the East Side, Browntown/Hedgeville and Baynard Boulevard.",
    "accessNotes": ["The city's historic districts include continuous brick rowhouse areas as well as larger early-20th-century homes, so lock hardware and entry conditions can differ block by block.","Market Street, Delaware Avenue, I-95 and the Riverfront street network create very different provider access patterns.","Turnover rekeys and lock changes are relevant for Wilmington's rowhouses, rentals, condos and small multifamily properties."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "newark-de",
    "name": "Newark",
    "shortLocation": "Newark, Delaware",
    "state": "Delaware",
    "group": "delaware",
    "kind": "city",
    "parent": null,
    "areas": ["Main Street","University of Delaware","Cleveland Avenue","South College Avenue","Elkton Road","Chapel Street"],
    "nearby": ["wilmington-de","middletown-de","dover-de","philadelphia-pa"],
    "localContext": "Newark combines university-area rentals and apartments with owner-occupied neighborhoods and townhouses around Main Street, Cleveland Avenue, South College Avenue, Elkton Road and Chapel Street.",
    "accessNotes": ["Student and rental turnover can create recurring rekey demand where former occupants may retain copies of keys.","University events and Main Street activity can affect curb access even when the service address is nearby.","A request should distinguish apartment-unit access from any common building entrance or managed property access."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "dover-de",
    "name": "Dover",
    "shortLocation": "Dover, Delaware",
    "state": "Delaware",
    "group": "delaware",
    "kind": "city",
    "parent": null,
    "areas": ["Downtown Dover","Loockerman Street","Silver Lake","North Dover","West Dover","South Dover","US 13 corridor"],
    "nearby": ["middletown-de","milford-de","wilmington-de","lewes-de"],
    "localContext": "Dover combines a historic downtown and compact residential streets with suburban neighborhoods, apartments and commercial development along US 13, Silver Lake, North Dover, West Dover and South Dover.",
    "accessNotes": ["Downtown and older residential properties can present different lock hardware from newer suburban housing.","US 13 and Route 1 approaches create different provider travel patterns from the compact downtown grid.","Move-in rekeys, landlord turnover work and smart-lock installation fit Dover's mix of rentals and owner-occupied homes."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "lewes-de",
    "name": "Lewes",
    "shortLocation": "Lewes, Delaware",
    "state": "Delaware",
    "group": "delaware",
    "kind": "city",
    "parent": null,
    "areas": ["Historic Lewes","Second Street","Pilottown","Savannah Road","Lewes Beach","Cape Henlopen area","Five Points area"],
    "nearby": ["rehoboth-beach-de","milford-de","dover-de","wilmington-de"],
    "localContext": "Lewes combines a historic town center, older residential streets, beach-area homes and expanding residential communities around Savannah Road and the Five Points area.",
    "accessNotes": ["Second homes and seasonal properties make trusted-access planning, rekeys and smart-lock installation especially relevant.","Summer traffic and beach-season parking can change provider access dramatically compared with off-season conditions.","Historic homes and newer coastal construction may involve very different door and lock hardware."],
    "propertyTags": ["property-management","real-estate","second-homes"]
  },
  {
    "slug": "rehoboth-beach-de",
    "name": "Rehoboth Beach",
    "shortLocation": "Rehoboth Beach, Delaware",
    "state": "Delaware",
    "group": "delaware",
    "kind": "city",
    "parent": null,
    "areas": ["Rehoboth Avenue","Boardwalk","North Rehoboth","South Rehoboth","Country Club Estates","Scarborough Avenue","Silver Lake"],
    "nearby": ["lewes-de","milford-de","dover-de","wilmington-de"],
    "localContext": "Rehoboth Beach is a compact coastal market with beach houses, condos, apartments and second homes around Rehoboth Avenue, the Boardwalk, North Rehoboth, South Rehoboth, Country Club Estates and Silver Lake.",
    "accessNotes": ["Second-home and vacation-property access is a core local use case, especially when owners are not on site.","Seasonal congestion can make exact-address matching and real provider acceptance more meaningful than a generic beach-town ETA.","Rekeys and smart-lock installations can support changes in owners, renters, cleaners or trusted local key holders."],
    "propertyTags": ["property-management","real-estate","second-homes"]
  },
  {
    "slug": "middletown-de",
    "name": "Middletown",
    "shortLocation": "Middletown, Delaware",
    "state": "Delaware",
    "group": "delaware",
    "kind": "city",
    "parent": null,
    "areas": ["Main Street","Silver Lake","Westown","Route 299","Levels Road","Summit Bridge Road","Appoquinimink area"],
    "nearby": ["newark-de","dover-de","wilmington-de","milford-de"],
    "localContext": "Middletown is a fast-growing suburban market with newer single-family neighborhoods, townhouses, apartments and an older town core around Main Street and Silver Lake.",
    "accessNotes": ["Newer housing makes move-in rekeys and smart-lock installation especially relevant.","Route 299, Levels Road and Summit Bridge Road spread requests across a broad suburban footprint.","Exact-address matching matters because a provider serving the town center may not automatically cover every outer subdivision."],
    "propertyTags": ["property-management","real-estate"]
  },
  {
    "slug": "milford-de",
    "name": "Milford",
    "shortLocation": "Milford, Delaware",
    "state": "Delaware",
    "group": "delaware",
    "kind": "city",
    "parent": null,
    "areas": ["Downtown Milford","Walnut Street","North Milford","South Milford","Mispillion River","US 113 corridor","Route 1 corridor"],
    "nearby": ["dover-de","lewes-de","rehoboth-beach-de","middletown-de"],
    "localContext": "Milford straddles Kent and Sussex counties and combines a compact downtown around the Mispillion River with suburban neighborhoods and highway-oriented development near US 113 and Route 1.",
    "accessNotes": ["Cross-county geography and highway approaches make exact service location important for provider matching.","Downtown properties and newer suburban homes can involve different lock hardware and access conditions.","Milford also works as a bridge market for second-home and coastal-property access needs farther south."],
    "propertyTags": ["property-management","real-estate","second-homes"]
  }
];

export const NORTHEAST_LOCAL_ROUTES = NORTHEAST_AREAS.map((area) => `/${area.slug}`);

export function getNortheastArea(slug: string) {
  return NORTHEAST_AREAS.find((area) => area.slug === slug);
}

export function getNortheastChildren(slug: string) {
  return NORTHEAST_AREAS.filter((area) => area.parent === slug);
}

export function getNortheastGroup(group: NortheastAreaGroup) {
  return NORTHEAST_AREAS.filter((area) => area.group === group);
}
